language: ruby
rvm:
  - 2.1.3

before_script:
  - "RAILS_ENV=test bundle exec rake db:setup"

notifications:
  email:
    recipients:
      - fk-enrolment@zeus.ugent.be
    on_success: never
    on_failure: change
    
  slack: zeuswpi:UNoxzGviaHfnoVebZqV6doJW
