development:
  secret_token: '95182ec21cccb3c5ca9425bb8a45ec9327ae7e33e857395b689f38fc6d801e1185c7abb662190c2b8512f05e8087f0bab0f604f802b4c631431811b5b1d32a29'
  secret_key_base: '95182ec21cccb3c5ca9425bb8a45ec9327ae7e33e857395b689f38fc6d801e1185c7abb662190c2b8512f05e8087f0bab0f604f802b4c631431811b5b1d32a29'

  fkbooks: 'http://www.fkgent.be/fkbooks/zeus_return_catcher/%d/%s'
  fkbooks_key: '#development#'

  fk_auth_url: 'http://fkgent.be/api_zeus_v2.php'
  fk_auth_salt: '#development#'
  fk_auth_key: '#development#'

  isic_api_wsdl: 'http://staging-isicregistrations.guido.be/service.asmx?WSDL'
  isic_api_user: 'ISICFK'
  isic_api_password: 'h4fs836t2U1'

  fk_gandalf_key: '#development#'

  citylife_key: '#development#'

test:
  secret_token: '95182ec21cccb3c5ca9425bb8a45ec9327ae7e33e857395b689f38fc6d801e1185c7abb662190c2b8512f05e8087f0bab0f604f802b4c631431811b5b1d32a29'
  secret_key_base: '95182ec21cccb3c5ca9425bb8a45ec9327ae7e33e857395b689f38fc6d801e1185c7abb662190c2b8512f05e8087f0bab0f604f802b4c631431811b5b1d32a29'

  fkbooks: 'http://www.fkgent.be/fkbooks/zeus_return_catcher/%d/%s'
  fkbooks_key: '#development#'

  fk_auth_url: 'http://fkgent.be/api_zeus_v2.php'
  fk_auth_salt: '#development#'
  fk_auth_key: '#development#'

  isic_api_wsdl: 'http://staging-isicregistrations.guido.be/service.asmx?WSDL'
  isic_api_user: 'ISICFK'
  isic_api_password: 'h4fs836t2U1'

  fk_gandalf_key: '#development#'

  citylife_key: '#development#'

staging:
  secret_token: '95182ec21cccb3c5ca9425bb8a45ec9327ae7e33e857395b689f38fc6d801e1185c7abb662190c2b8512f05e8087f0bab0f604f802b4c631431811b5b1d32a29'
  secret_key_base: '95182ec21cccb3c5ca9425bb8a45ec9327ae7e33e857395b689f38fc6d801e1185c7abb662190c2b8512f05e8087f0bab0f604f802b4c631431811b5b1d32a29'

  fk_auth_url: 'http://fkgent.be/api_isengard_v2.php'
  fk_auth_salt: '#development#'
  fk_auth_key: '#development#'

  fkbooks: 'http://www.fkgent.be/fkbooks/zeus_return_catcher/%d/%s'
  fkbooks_key: '#development#'

  isic_api_wsdl: 'http://staging-isicregistrations.guido.be/service.asmx?WSDL'
  isic_api_user: 'ISICFK'
  isic_api_password: 'h4fs836t2U1'

  fk_gandalf_key: '#development#'

  citylife_key: '#development#'

production:
  secret_token: '95182ec21cccb3c5ca9425bb8a45ec9327ae7e33e857395b689f38fc6d801e1185c7abb662190c2b8512f05e8087f0bab0f604f802b4c631431811b5b1d32a29'
  secret_key_base: '95182ec21cccb3c5ca9425bb8a45ec9327ae7e33e857395b689f38fc6d801e1185c7abb662190c2b8512f05e8087f0bab0f604f802b4c631431811b5b1d32a29'

  fk_auth_url: 'http://fkgent.be/api_zeus_v2.php'
  fk_auth_salt: '#development#'
  fk_auth_key: '#development#'

  fkbooks: 'http://www.fkgent.be/fkbooks/zeus_return_catcher/%d/%s'
  fkbooks_key: '#development#'

  isic_api_wsdl: 'http://staging-isicregistrations.guido.be/service.asmx?WSDL'
  isic_api_user: 'ISICFK'
  isic_api_password: 'h4fs836t2U1'

  fk_gandalf_key: '#development#'

  citylife_key: '#development#'
